//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storyunit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boek
    {
        public int BoekID { get; set; }
        public int AuteurID { get; set; }
        public int UitgeverID { get; set; }
        public int TaalID { get; set; }
        public string Titel { get; set; }
        public string Afmeting { get; set; }
        public string Gewicht { get; set; }
        public string Druk { get; set; }
        public string ISBN { get; set; }
        public string Fotolink { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Boek Boek1 { get; set; }
        public virtual Boek Boek2 { get; set; }
        public virtual Taal Taal { get; set; }
        public virtual Uitgever Uitgever { get; set; }
    }
}
