//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storyunit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbStoryunitEntities : DbContext
    {
        public dbStoryunitEntities()
            : base("name=dbStoryunitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteur { get; set; }
        public virtual DbSet<Boek> Boek { get; set; }
        public virtual DbSet<Taal> Taal { get; set; }
        public virtual DbSet<Tijdschrift> Tijdschrift { get; set; }
        public virtual DbSet<Uitgever> Uitgever { get; set; }
    
        public virtual ObjectResult<spAllboeken_Result> spAllboeken()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllboeken_Result>("spAllboeken");
        }
    
        public virtual ObjectResult<spAllboekenAuteur_Result> spAllboekenAuteur(string auteur)
        {
            var auteurParameter = auteur != null ?
                new ObjectParameter("auteur", auteur) :
                new ObjectParameter("auteur", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllboekenAuteur_Result>("spAllboekenAuteur", auteurParameter);
        }
    
        public virtual ObjectResult<spAllboekenTaal_Result> spAllboekenTaal(string taal)
        {
            var taalParameter = taal != null ?
                new ObjectParameter("Taal", taal) :
                new ObjectParameter("Taal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllboekenTaal_Result>("spAllboekenTaal", taalParameter);
        }
    
        public virtual ObjectResult<spAllTijdschriften_Result> spAllTijdschriften()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllTijdschriften_Result>("spAllTijdschriften");
        }
    
        public virtual ObjectResult<spAllTijdschriftenAuteur_Result> spAllTijdschriftenAuteur(string auteur)
        {
            var auteurParameter = auteur != null ?
                new ObjectParameter("auteur", auteur) :
                new ObjectParameter("auteur", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllTijdschriftenAuteur_Result>("spAllTijdschriftenAuteur", auteurParameter);
        }
    
        public virtual ObjectResult<spAllTijdschriftenTaal_Result> spAllTijdschriftenTaal(string taal)
        {
            var taalParameter = taal != null ?
                new ObjectParameter("Taal", taal) :
                new ObjectParameter("Taal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAllTijdschriftenTaal_Result>("spAllTijdschriftenTaal", taalParameter);
        }
    }
}
