//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storyunit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbStoryunitEntities : DbContext
    {
        public dbStoryunitEntities()
            : base("name=dbStoryunitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteur { get; set; }
        public virtual DbSet<Boek> Boek { get; set; }
        public virtual DbSet<Taal> Taal { get; set; }
        public virtual DbSet<Tijdschrift> Tijdschrift { get; set; }
        public virtual DbSet<Uitgever> Uitgever { get; set; }
    }
}
