//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storyunit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tijdschrift
    {
        public int TijdschriftID { get; set; }
        public int AuteurID { get; set; }
        public int UitgeverID { get; set; }
        public int TaalID { get; set; }
        public string Titel { get; set; }
        public string Uitgifte { get; set; }
        public string Afmeting { get; set; }
        public string ISSN { get; set; }
        public string Fotolink { get; set; }
    
        public virtual Auteur Auteur { get; set; }
        public virtual Taal Taal { get; set; }
        public virtual Tijdschrift Tijdschrift1 { get; set; }
        public virtual Tijdschrift Tijdschrift2 { get; set; }
        public virtual Uitgever Uitgever { get; set; }
    }
}
